package com.moyz.adi.common.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.databind.JsonNode;
import com.moyz.adi.common.base.JsonNodeTypeHandler;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.apache.ibatis.type.JdbcType;

@EqualsAndHashCode(callSuper = true)
@Data
@TableName(value = "adi_draw", autoResultMap = true)
@Schema(title = "ai images", description = "Image generated by ai")
public class Draw extends BaseEntity {
    //用户ID
    @TableField("user_id")
    private Long userId;
    //绘图任务的UUID
    @TableField("uuid")
    private String uuid;
    //图像模型id
    @TableField("ai_model_id")
    private Long aiModelId;
    //图像模型名称
    @TableField("ai_model_name")
    private String aiModelName;
    //生成图片的提示词
    @TableField("prompt")
    private String prompt;

    @TableField("negative_prompt")
    private String negativePrompt;
    //生成图片的尺寸
    @TableField("generate_size")
    private String generateSize;
    //生成图片的质量
    @TableField("generate_quality")
    private String generateQuality;
    //生成图片的数量，必须在1到10之间，默认为1
    @TableField("generate_number")
    private Integer generateNumber;
    //生成图片的随机种子，如果希望生成内容保持相对稳定，请使用相同的seed参数值
    @TableField("generate_seed")
    private Integer generateSeed;

    @TableField(value = "dynamic_params", jdbcType = JdbcType.JAVA_OBJECT, typeHandler = JsonNodeTypeHandler.class)
    private JsonNode dynamicParams;
    //原始图片的UUID，交互方式必须为2或3
    @Schema(title = "file uuid")
    @TableField("original_image")
    private String originalImage;
    //遮罩图片的UUID，交互方式必须为2
    @Schema(title = "file uuid")
    @TableField("mask_image")
    private String maskImage;
    //从OpenAI响应生成图片的URL，逗号隔开
    @TableField("resp_images_path")
    private String respImagesPath;
    //生成的多张图片文件UUID，逗号隔开
    @Schema(title = "generated image uuids")
    @TableField("generated_images")
    private String generatedImages;
    //交互方式：1：文本生成图片；2：图片编辑；3：图片生成图片；4：背景生成；5：扩大图片；6：风格转化
    @TableField("interacting_method")
    private Integer interactingMethod;
    //任务执行状态，1：进行中，2：失败，3：成功
    @TableField("process_status")
    private Integer processStatus;
    //生成图片状态备注
    @TableField("process_status_remark")
    private String processStatusRemark;
    //是否公开
    @TableField("is_public")
    private Boolean isPublic;
    //是否带水印
    @TableField("with_watermark")
    private Boolean withWatermark;
    //点赞数
    @TableField("star_count")
    private Integer starCount;
}
